### ISSUE TITLE
Compatibility with databases created by older/current Sacred versions 

### ISSUE THREAD

**Issue by flukeskywalker** [chovanecm/sacredboard#20]
Hi,

It appears that sacredboard can not be used with databases created by sacred v6.* since the runs are in `db.prefix.runs` instead of `db.prefix`. 

`prefix` was usually `default`, but is now `runs`. So sacredboard is trying to look into `db.runs` whereas my runs are in `db.default.runs`.

This appears to be an important issue for many users like me who have older sacred databases that we would like to browse. Is there a plan to provide compatibility with older databases?

**Comment by chovanecm** [comment]
Hi,

I've already noticed some backward compatibility issues (with different
types of primary keys used by versions 0.6 and 0.7).

But I was not aware of this problem.
Thank you for your investigation of the cause.

I'll have a look at it asap.

čt 16. 2. 2017 v 17:09 odesílatel Rupesh Kumar Srivastava <
notifications@github.com> napsal:

**Comment by chovanecm** [comment]
I've checked Sacred code and the database has indeed changed. The **default** collection is now indeed called `runs` instead of `default.runs`. However, when running an experiment, the user is allowed to choose the collection name. Therefore, it should be allowed to select the collection in sacredboard as well.

Before I come up with something more convenient, would you accept a command line option to set the collection name manually?

**Comment by flukeskywalker** [comment]
That would definitely be helpful. And I agree -- since the user has the option to select the collection name (although hardly anyone ever does it, I think), something like this feature is likely to stay.

**Comment by chovanecm** [comment]
Ok, I added the option (it's called `-mc`). You can update to the latest version by running `pip install --upgrade sacredboard`. Please see the readme or run `sacredboard --help` for examples.
